from setuptools import setup, find_packages

setup(
    name="plot_extract",
    version="0.1",
    packages=find_packages(),
    install_requires=[
        "beautifulsoup4==4.12.3",
        "importlib_metadata==7.1.0",
        "imutils==0.5.4",
        "ipykernel==6.29.5",
        "ipython==8.26.0",
        "joblib==1.4.2",
        "jupyter_client==8.6.2",
        "jupyter_core==5.7.2",
        "kiwisolver==1.4.5",
        "libclang==18.1.1",
        "Markdown==3.6",
        "markdown-it-py==3.0.0",
        "matplotlib==3.9.1",
        "matplotlib-inline==0.1.7",
        "mdurl==0.1.2",
        "ml-dtypes==0.4.0",
        "mlflow==2.14.3",
        "mpmath==1.3.0",
        "nltk==3.9.1",
        "numpy==1.26.4",
        "opencv-python==4.10.0.84",
        "pandas==2.2.2",
        "pillow==10.4.0",
        "pyparsing==3.1.2",
        "PyQt5==5.15.11",
        "PyQt5-Qt5==5.15.14",
        "PyQt5_sip==12.15.0",
        "regex==2024.7.24",
        "scikit-learn==1.5.1",
        "scipy==1.14.0",
        "seaborn==0.13.2",
        "torch==2.4.1",
        "torchaudio==2.4.1",
        "torchinfo==1.8.0",
        "torchvision==0.19.1",
        "tqdm==4.66.4"
    ],
    include_package_data=True,
    description="A package to degitalize plots from images",
    long_description=open("README.md").read(),
    author="Ruben Khachaturyan",
    author_email="dr.khachaturyan@gmail.com",
    url="https://github.com/khachaturyan-1991/PlotExtract",
    classifiers=["Development Status :: 3 - Alpha",
                 "Programming Language :: Python :: 3",
                 "License :: OSI Approved :: MIT License",
                 "Operating System :: OS Independent",
                 ],
    python_requires=">=3.6"
)
